#postgresql
[PostgreSQL]
    TypeP = "postgres"
    Host = "43.139.123.205"
    Port = 5432
    Dbuser = "root12"
    DbPassWord = "root12"
    DbName = "root12"
#redis
[Redis]
    HostR = "43.139.123.205"
    PortR = 6379
    #DbUserR = "root"
    DbPassWordR = "root"
    DBModel = 1
#Jwtk
[JwtK]
    JwtKey = "253157896"

#Jwtk
[SetModel]
    AppNode = "debug"
    AppNode2 = "release"

[Discover]
    nodes =[""]

[Cache]
    CacheMusicListenCount = "music_listened_count"
    CacheMusicLikeCount = "music_musiclike_count"
    CacheMusicSortCount = "music_musicsort_count"
    CacheMusicListLikeCount = "music_musiclistlike_count"
    CacheMusicListSortCount = "music_musiclistsort_count"
    CacheArticleReadCount = "music_articleread_count"
    CacheArticleCommentCount = "music_articlecomment_count"
    CacheArticleLikeCount = "music_articlike_count"
    CacheArticleForward = "music_articforward_count"
    CacheCommentLikeCount = "music_commentlike_count"
    CacheMusicDayListen = "music_musicdaylisten_count"
    CacheMusicListDayListen = "music_musiclistdaylisten_count"
[Rank]
    CacheRankMusicListYear = "musiclistYear_rank"
    CacheRankMusicListMonth = "musiclistMonth_rank"
    CacheRankMusicListWeek = "musiclistWeek_rank"
    CacheRankMusicListDay = "musiclistDay_rank"
    CacheRankMusicYear = "musicYear_rank"
    CacheRankMusicMonth = "musicMonth_rank"
    CacheRankMusicWeek = "musicWeek_rank"
    CacheRankMusicDay = "musicDay_rank"

[TencentCos]
    Url = "https://yamada-bucket-1314757920.cos.ap-guangzhou.myqcloud.com"
    SecretId = "AKIDLmASgkcLyWu9umaHm8LQPGxUpjVDmHdN"
    SecretKey = "kdMxOemiSylOwPq8ybEjGiCxc7RbcVKC"

[SFtp]
    User = "root"
    Password = "cjk7588@"
    Host = "43.139.123.205"
    Port = "22"

[FileGrpc]
    Server = ["localhost:5051"]
